In [1]:
import numpy as np

In [2]:
np.__version__

'2.5.0'

In [3]:
my_list = [1, 2, 3, 4]
my_list

[1, 2, 3, 4]

__vectorized operations__

In [4]:
array = np.array(my_list)
array

array([1, 2, 3, 4])

In [5]:
array * 2

array([2, 4, 6, 8])

__multidimensional arrays__

In [7]:
array = np.array("A")
array.ndim
# 0

0

In [8]:
array = np.array(['A', 'B', 'C'])
array.ndim

1

In [10]:
array = np.array([[['A', 'B', 'C'], ['D', "E", "F"], ["G", "H", 'I']],
                  [['J', 'k', 'l'], ['m', "n", "o"], ["p", "q", 'r']],
                  [['s', 't', 'u'], ['v', "w", "x"], ["y", "z", ' ']]
                  ])
array.ndim

3

In [11]:
array.shape

(3, 3, 3)

In [14]:
array[0][0]

array(['A', 'B', 'C'], dtype='<U1')

In [15]:
array[0, 0]

array(['A', 'B', 'C'], dtype='<U1')

In [16]:
array[0, 0, 0]

np.str_('A')

__Construct a word using this three dimensional numpy array__

In [17]:
# array = np.array([[['A', 'B', 'C'], ['D', "E", "F"], ["G", "H", 'I']],
#                   [['J', 'k', 'l'], ['m', "n", "o"], ["p", "q", 'r']],
#                   [['s', 't', 'u'], ['v', "w", "x"], ["y", "z", ' ']]
#                   ])
word = array[0, 0, 1] + array[2, 0, 2] + array[2, 0, 0]
word

'Bus'

__slicing__

In [18]:
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])


In [19]:
# array[start:end:step]
array[0]

array([1, 2, 3, 4])

In [20]:
array[1]

array([5, 6, 7, 8])

In [21]:
array[2]

array([ 9, 10, 11, 12])

In [22]:
array[3]

array([13, 14, 15, 16])

In [23]:
array[-1]

array([13, 14, 15, 16])

In [24]:
array[-2]

array([ 9, 10, 11, 12])

In [25]:
array[-3]

array([5, 6, 7, 8])

In [26]:
array[-4]

array([1, 2, 3, 4])

In [27]:
array[0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
array[0:4:2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [30]:
array[::-1]

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [31]:
array[:, 0]

array([ 1,  5,  9, 13])

In [32]:
array[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [33]:
array[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [37]:
array[0:2, 2:]

array([[3, 4],
       [7, 8]])

__Arithmetic__

- Scalar arithmetic

In [39]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

In [40]:
array + 1

array([2, 3, 4])

In [41]:
array

array([1, 2, 3])

In [42]:
array - 2

array([-1,  0,  1])

In [44]:
array * 3

array([3, 6, 9])

In [45]:
array / 4

array([0.25, 0.5 , 0.75])

In [46]:
array ** 5

array([  1,  32, 243])

- Vectorized math funcs

In [47]:
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081])

In [48]:
array2 = np.array([1.01, 2.5, 3.99])

In [49]:
np.round(array2) #floor, ceil

array([1., 2., 4.])

In [50]:
array2 = array

In [51]:
array2

array([1, 2, 3])

In [52]:
array + array2

array([2, 4, 6])

In [53]:
array - array2

array([0, 0, 0])

In [54]:
array * array2

array([1, 4, 9])

Exponential and logarithmic functions

In [55]:
np.exp(array) # e^x

array([ 2.71828183,  7.3890561 , 20.08553692])

In [56]:
np.exp2(array) # 2^x

array([2., 4., 8.])

In [57]:
np.log(array) # natural log

array([0.        , 0.69314718, 1.09861229])

In [58]:
np.log10(array) #base-10 log

array([0.        , 0.30103   , 0.47712125])

In [59]:
np.log2(array) #base-2 log

array([0.       , 1.       , 1.5849625])

Trigonometric functions

In [61]:
np.sin(array)

array([0.84147098, 0.90929743, 0.14112001])

In [62]:
np.cos(array)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [63]:
np.tan(array)

array([ 1.55740772, -2.18503986, -0.14254654])

Absolute and sign functions

In [64]:
np.abs(array)

array([1, 2, 3])

In [65]:
np.fabs(array)

array([1., 2., 3.])

In [66]:
np.sign(array)

array([1, 1, 1])

Statistical functions

In [67]:
np.mean(array) #the mathematical average of a set of number

np.float64(2.0)

In [69]:
np.median(array) #the middle value in an ordered dataset

np.float64(2.0)

In [72]:
np.std(array) #насколько сильно значение в наборе данных разбросаны относительно среднего значения
#маленькое стд -> данные расположены близко к среднему
#большое -> данные сильно разбросаны

np.float64(0.816496580927726)

In [73]:
np.var(array) #use in pca, statistical tests. STD^2

np.float64(0.6666666666666666)

In [74]:
np.min(array)

np.int64(1)

In [75]:
np.max(array)

np.int64(3)

In [76]:
np.sum(array)

np.int64(6)

In [77]:
np.prod(array) #product, multiplies all values inside of array

np.int64(6)

Comparison functions

In [78]:
np.maximum(array, array2)
np.minimum(array, array2)

array > 2
array2 == 3
np.equal(array, array2)
np.greater(array, array2)

array([False, False, False])

Linear algebra operations

In [79]:
array @ array2

np.int64(14)

In [80]:
np.dot(array, array2)

np.int64(14)

In [82]:
np.cumsum(array)

array([1, 3, 6])

ML prioritized

In [83]:
np.array([1, 2, 3]) #createas numpy array

array([1, 2, 3])

In [84]:
np.arange(5) # creates 12345 also has arange(start, end, step)

array([0, 1, 2, 3, 4])

In [86]:
np.linspace(0, 10, 5)
"""
returns evenly spaced numbers over a specified mathematical interval. You specify the starting point, the stopping point, and the total number of samples you want, and NumPy automatically calculates the correct spacing between each element
"""

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [87]:
a = np.arange(6)
print(a)
a.reshape(2,3) #Changes the shape of an array.

[0 1 2 3 4 5]


array([[0, 1, 2],
       [3, 4, 5]])

In [88]:
A = np.array([[1,2],
              [3,4]])

A.T #Swaps rows and columns.

array([[1, 3],
       [2, 4]])

In [89]:
np.mean([1,2,3,4]) #Calculates the average.

np.float64(2.5)

In [90]:
np.std([1,2,3,4]) #Calculates standard deviation.

np.float64(1.118033988749895)

In [91]:
np.sum([1,2,3]) #Adds everything.

np.int64(6)

In [92]:
np.min([5,8,2,9]) #Finds smallest value.

np.int64(2)

In [93]:
np.max([5,8,2,9]) #Finds largest value.

np.int64(9)

In [ ]:
np.sqrt([1,4,9]) #Square root.

In [94]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

A @ B #Performs matrix multiplication.

array([[19, 22],
       [43, 50]])

In [95]:
x = [3,4]

np.linalg.norm(x)#Calculates vector length.

np.float64(5.0)

In [96]:
a = [5,9,2,1]
np.argmax(a) #Returns the position of the largest value.

np.int64(1)

In [97]:
a = np.array([1,2,3,4])

np.where(a>2, 1, 0) #Conditional operation.

array([0, 0, 1, 1])

__Filtering__


In [98]:
ages = np.array([
    [21, 17, 19, 20, 16, 30, 18, 65],
    [39, 22, 15, 99, 18, 19, 20, 21]
])

In [99]:
teenagers = ages[ages < 18]
teenagers

array([17, 16, 15])

In [103]:
adults = ages[(ages >= 18) & (ages < 65)]
adults

array([21, 19, 20, 30, 18, 39, 22, 18, 19, 20, 21])

In [104]:
np.sort(adults)

array([18, 18, 19, 19, 20, 20, 21, 21, 22, 30, 39])

In [105]:
adults

array([21, 19, 20, 30, 18, 39, 22, 18, 19, 20, 21])

In [106]:
seniors = ages[ages >= 65]
seniors

array([65, 99])

In [107]:
evens = ages[ages % 2 == 0]
evens

array([20, 16, 30, 18, 22, 18, 20])

In [108]:
odds = ages[ages % 2 != 0]
odds

array([21, 17, 19, 65, 39, 15, 99, 19, 21])

In [109]:
adults = np.where(ages >= 18, ages, -1)
adults

array([[21, -1, 19, 20, -1, 30, 18, 65],
       [39, 22, -1, 99, 18, 19, 20, 21]])