In [5]:
import torch
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
torch.__version__

'2.13.0+cu126'

### Introduction to Tensors
### Creating Tensors

In [7]:
# scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [10]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [19]:
matrix = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
matrix

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [20]:
matrix.ndim

2

In [21]:
matrix.shape

torch.Size([3, 2])

In [22]:
matrix.shape[0]

3

In [23]:
tensor = torch.tensor([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
])

In [24]:
tensor.shape

torch.Size([1, 3, 3])

In [25]:
tensor.ndim

3

In [26]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## Random tensors

In [27]:
random_tensor = torch.rand(3, 4)

In [28]:
random_tensor

tensor([[0.4210, 0.6519, 0.9329, 0.2548],
        [0.0406, 0.6805, 0.6717, 0.0454],
        [0.1143, 0.6099, 0.2640, 0.5053]])

In [29]:
torch.randn(3, 4) * 0.01

tensor([[-0.0051,  0.0061, -0.0217,  0.0025],
        [ 0.0181,  0.0025,  0.0045,  0.0009],
        [-0.0028,  0.0113,  0.0068, -0.0039]])

In [30]:
random_tensor.shape

torch.Size([3, 4])

In [31]:
random_tensor.ndim

2

In [33]:
random_tensor2 = torch.rand(10, 10, 10)
random_tensor2

tensor([[[2.1687e-03, 4.1907e-01, 6.6073e-01, 8.5374e-01, 3.9260e-01,
          8.9348e-01, 2.0269e-01, 5.0346e-01, 2.3532e-01, 4.7790e-01],
         [1.3897e-01, 2.9166e-01, 5.1485e-01, 6.8762e-01, 5.7894e-01,
          1.5363e-01, 9.7775e-01, 6.2638e-01, 5.6098e-01, 9.3703e-01],
         [2.1336e-01, 3.2652e-01, 8.6820e-01, 3.3633e-01, 8.4751e-01,
          2.0345e-01, 9.7089e-01, 8.2920e-01, 2.6154e-01, 9.4454e-02],
         [2.4634e-01, 8.9134e-02, 4.2696e-01, 2.2928e-01, 7.3567e-01,
          2.9957e-01, 6.4206e-01, 1.9639e-01, 9.1164e-01, 4.3961e-01],
         [3.7916e-01, 7.6787e-01, 1.7095e-01, 7.7157e-01, 8.4681e-01,
          9.9131e-01, 3.5663e-02, 3.7717e-01, 1.2413e-01, 1.7066e-01],
         [3.5526e-01, 6.9306e-01, 9.8100e-01, 3.6179e-01, 4.3167e-02,
          8.7538e-01, 5.1672e-01, 6.2086e-02, 3.1965e-01, 1.0740e-01],
         [9.4819e-01, 4.3154e-01, 1.2741e-01, 2.7857e-01, 9.1360e-01,
          6.2432e-01, 3.7872e-02, 9.1923e-01, 2.9688e-01, 7.9207e-01],
         [8.6

In [34]:
random_tensor2.reshape((1000, -1))

tensor([[2.1687e-03],
        [4.1907e-01],
        [6.6073e-01],
        [8.5374e-01],
        [3.9260e-01],
        [8.9348e-01],
        [2.0269e-01],
        [5.0346e-01],
        [2.3532e-01],
        [4.7790e-01],
        [1.3897e-01],
        [2.9166e-01],
        [5.1485e-01],
        [6.8762e-01],
        [5.7894e-01],
        [1.5363e-01],
        [9.7775e-01],
        [6.2638e-01],
        [5.6098e-01],
        [9.3703e-01],
        [2.1336e-01],
        [3.2652e-01],
        [8.6820e-01],
        [3.3633e-01],
        [8.4751e-01],
        [2.0345e-01],
        [9.7089e-01],
        [8.2920e-01],
        [2.6154e-01],
        [9.4454e-02],
        [2.4634e-01],
        [8.9134e-02],
        [4.2696e-01],
        [2.2928e-01],
        [7.3567e-01],
        [2.9957e-01],
        [6.4206e-01],
        [1.9639e-01],
        [9.1164e-01],
        [4.3961e-01],
        [3.7916e-01],
        [7.6787e-01],
        [1.7095e-01],
        [7.7157e-01],
        [8.4681e-01],
        [9

random tensor with a shape of an image

In [35]:
random_image_size = torch.rand(size=(224, 224, 3))
random_image_size.shape, random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

create zeros and ones tensor

In [36]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
one = torch.ones(3, 4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
zero.dtype, one.dtype

(torch.float32, torch.float32)

range tensor

In [47]:
odd_range_tensor = torch.arange(start=1, end=11, step=2, dtype=torch.int64)
odd_range_tensor

tensor([1, 3, 5, 7, 9])

In [48]:
torch.zeros(10, dtype=torch.int64)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

datatypes

In [49]:
float_tensor = torch.rand(3, dtype=torch.float32, device='cuda', requires_grad=False) #also can be float16, float64

In [50]:
"""
data type is with what data type tensor is or will be created
we need different types of the same data type for precision in computing. It means that - Precision refers to how many bits are used to represent a number, which determines how much numeric detail (how many significant digits) you can store before rounding error creeps in. but with higher precision we sacrifice the computing speed but the calculations will be more precise. Number means bit


device means which device to use for computing. We can choose either cpu or cuda(gpu only for NVIDIA GPUs)

requires_grad means should i track gradients or not
"""

'\ndata type is with what data type tensor is or will be created\nwe need different types of the same data type for precision in computing. It means that - Precision refers to how many bits are used to represent a number, which determines how much numeric detail (how many significant digits) you can store before rounding error creeps in. but with higher precision we sacrifice the computing speed but the calculations will be more precise. Number means bit\n\n\ndevice means which device to use for computing. We can choose either cpu or cuda(gpu only for NVIDIA GPUs)\n\nrequires_grad means should i track gradients or not\n'

In [54]:
float_tensor2 = torch.rand(3, dtype=torch.float64, device='cuda', requires_grad=False)

In [55]:
(float_tensor * float_tensor2).dtype

torch.float64

### Getting information from tensors:
1. Tensors not right data type -> use `tensor.dtype` for info
2. Tensors not right shape -> use `tensor.shape` for info
3. Tensors not right device -> use `tensor.device` or `torch.cuda.is_available` for info

In [56]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6741, 0.9286, 0.9298, 0.9653],
        [0.8217, 0.4417, 0.3546, 0.3646],
        [0.6294, 0.3358, 0.3635, 0.1503]])

In [57]:
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating tensors

Operatiosn include:

* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix multiplication

In [58]:
tensor_operation = torch.tensor([1, 2, 3])
tensor_operation + 10

tensor([11, 12, 13])

In [59]:
tensor_operation * 10

tensor([10, 20, 30])

In [60]:
tensor_operation - 10

tensor([-9, -8, -7])

In [61]:
torch.mul(tensor_operation, 10)

tensor([10, 20, 30])

In [62]:
torch.add(tensor_operation, 10)

tensor([11, 12, 13])

In [64]:
torch.matmul(tensor_operation, tensor_operation), tensor_operation @ tensor_operation

(tensor(14), tensor(14))

In [65]:
tensor_operation2 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]])

In [68]:
torch.matmul(tensor_operation2, tensor_operation2.T), tensor_operation2 @ tensor_operation2.T
#to get correct multiplication we must follow 2 rules:
# inner dimensions must match
# the output of mult will result in outer dimensions size:
# 2, 3 and 2, 3 -> won't work
# 2, 3 and 3, 2 -> will work, new output: 2, 2
# 3, 2 and 2, 3 -> will work, new output: 3, 3

(tensor([[14, 32],
         [32, 77]]),
 tensor([[14, 32],
         [32, 77]]))

# Tensor aggregations

In [73]:
x = torch.arange(start=0, end=100, step=10, dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [74]:
x.min(), torch.min(x)

(tensor(0.), tensor(0.))

In [75]:
x.max(), torch.max(x)

(tensor(90.), tensor(90.))

In [78]:
x.mean(), torch.mean(x.type(torch.float16)).dtype # casting type: torch.type
#mean requires floating number, cant work with long

(tensor(45.), torch.float16)

In [79]:
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

In [80]:
x.argmin(), x.argmax(), torch.argmin(x), torch.argmax(x) #positions of asked value

(tensor(0), tensor(9), tensor(0), tensor(9))

In [81]:
x[0], x[9]

(tensor(0.), tensor(90.))

## Reshaping, squeezing, stacking, unsqueezing:
* Reshaping - reshapes an input to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other `(vstack)` or side by side `(hstack)`
* Squeeze - remove all 1 dimensions from tensor
* Unsqueeze - adds 1 dimension to tensor
* Permute - return a view of the input with dimensions permuted in a certain way

In [92]:
x2 = torch.arange(1, 13, dtype=torch.float32)
x2, x2.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [93]:
x2_reshaped = x2.reshape(3, 4)
x2_reshaped, x2_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [95]:
z = x2.view(4, 3) # allows to share the same memory from origin matrix
z

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [96]:
x2

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [97]:
z[:, 0] = 5

In [98]:
x2

tensor([ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.])

In [99]:
z

tensor([[ 5.,  2.,  3.],
        [ 5.,  5.,  6.],
        [ 5.,  8.,  9.],
        [ 5., 11., 12.]])

In [108]:
x2_stacked = torch.stack([x2, x2, x2, x2], dim=1)

In [109]:
x2_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 5.,  5.,  5.,  5.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [ 5.,  5.,  5.,  5.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [116]:
x_zeros = torch.zeros(2, 1, 2, 1, 2)
x_zeros_squeezed = x_zeros.squeeze()
x_zeros_squeezed.shape

torch.Size([2, 2, 2])

In [125]:
x_zeros_squeezed.unsqueeze(dim=3).shape

torch.Size([2, 2, 2, 1])

In [126]:
x_orig = torch.rand(size=(224, 224, 3))
x_permuted = x_orig.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

# Indexing, selecting data from tensor

In [127]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [128]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [131]:
x[0, 0], x[0, 1]

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [132]:
x[0, 0, 0]

tensor(1)

In [133]:
x[:, 0]

tensor([[1, 2, 3]])

In [134]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [135]:
x[:, 1, 1]

tensor([5])

# Transitions between numpy and pytorch array
* Numpy -> Tensor: `torch.from_numpy(ndarray)`
* Tensor -> Numpy: `torch.Tensor.numpy()`

In [138]:
array = np.arange(1, 8)
tensor = torch.from_numpy(array)
array.dtype, tensor.dtype # since numpy default dtype is long it transferred automatically in pytorch

(dtype('int64'), torch.int64)

In [139]:
array = torch.Tensor.numpy(tensor)
array

array([1, 2, 3, 4, 5, 6, 7])

# Reproducibility (trying to take random out of random)

In short, how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

That loop is training. Every weight starts as a random number (that torch.randn() * 0.01 from earlier), the forward pass runs tensor operations on it, the loss tells you how wrong it was, and backprop nudges the random numbers to be slightly less random — slightly more tuned to the actual data. Repeat thousands of times, and "random" gradually becomes "learned."

The problem: because it starts random and gets nudged by random data shuffling too, every run is different by default — different starting weights, different training order. Fine for real training, bad for debugging or comparing two versions of your code, because you can't tell if a change in results came from your code or from a new roll of random numbers.

torch.manual_seed(42) is how you take the "random" back out of random — pin the pseudo-random generator to always produce the same sequence, so reruns are identical and comparisons are fair.

Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

1. Getting a GPU
   1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
   2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get: https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/
   3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

In [144]:
#check cuda availability
device = 'cuda' if torch.cuda.is_available() else 'cpu'
ra = torch.tensor(1, device=device)

In [145]:
ra.device

device(type='cuda', index=0)

In [146]:
#move to a device
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4, 5, 6, 7], device='cuda:0')

In [148]:
#back to cpu and also can't do to numpy if device is cuda
tensor_on_cpu = tensor_on_gpu.cpu() # or to('cpu'), works both way