In [1]:
from transformers import AutoTokenizer

C:\Users\user\Desktop\MlLibraries\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tokenizer = AutoTokenizer.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english')
tokenizer

C:\Users\user\Desktop\MlLibraries\.venv\Lib\site-packages\huggingface_hub\file_download.py:150: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in D:\huggingface_cache\hub\models--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


BertTokenizer(name_or_path='distilbert-base-uncased-finetuned-sst-2-english', vocab_size=30522, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
})

In [3]:
sentences = ["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!"]

In [4]:
inputs = tokenizer(sentences, padding=True, truncation=True,return_tensors='pt')

why padding:
Sentence A → 8 tokens
Sentence B → 5 tokens

output without padding:
[
  [8 values],
  [5 values]
]

after padding:
A: [t1 t2 t3 t4 t5 t6 t7 t8]
B: [t1 t2 t3 t4 t5 PAD PAD PAD]

and the transformer can process both sentences together as one batch.

truncation=True exists because transformers cannot accept arbitrarily long sequences.

For example: max sequence length = 512
but: 800 tokens

but llm cant just do 800 tokens so we truncate

In [5]:
inputs

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

The vector output by the Transformer module is usually large. It generally has three dimensions:

- Batch size: The number of sequences processed at a time (2 in our example).
- Sequence length: The length of the numerical representation of the sequence (16 in our example).
- Hidden size: The vector dimension of each model input.

In [ ]:
"""
The AutoModel class and its associates are actually simple wrappers designed to fetch the appropriate model architecture for a given checkpoint. It’s an “auto” class meaning it will guess the appropriate model architecture for you and instantiate the correct model class. However, if you know the type of model you want to use, you can use the class that defines its architecture directly:
"""

In [ ]:
from transformers import BertModel

model = BertModel.from_pretrained("bert-base-cased")

In [ ]:
"""
Also you can save model
"""

In [ ]:
model.save_pretrained('directory')

In [ ]:
"""
will save 2 files:
ls directory_on_my_computer

config.json model.safetensors
"""

If you look inside the config.json file, you’ll see all the necessary attributes needed to build the model architecture. This file also contains some metadata, such as where the checkpoint originated and what 🤗 Transformers version you were using when you last saved the checkpoint.

The pytorch_model.safetensors file is known as the state dictionary; it contains all your model’s weights. The two files work together: the configuration file is needed to know about the model architecture, while the model weights are the parameters of the model.

In [1]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

C:\Users\user\Desktop\MlLibraries\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\user\Desktop\MlLibraries\.venv\Lib\site-packages\huggingface_hub\file_download.py:150: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in D:\huggingface_cache\hub\models--bert-base-cased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, 

In [5]:
tokenizer('Using a Transformer network is simple')['input_ids']

[101, 7993, 170, 13809, 23763, 2443, 1110, 3014, 102]

In [ ]:
#tokenizer.save_pretrained('path')

In [4]:
sequence = "Using a Transformer network is simple"
tokens = tokenizer.tokenize(sequence)

print(tokens)

['Using', 'a', 'Trans', '##former', 'network', 'is', 'simple']


In [7]:
ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)

[7993, 170, 13809, 23763, 2443, 1110, 3014]


In [8]:
sentence = "I’ve been waiting for a HuggingFace course my whole life."
tokenizer(sentence)

{'input_ids': [101, 146, 787, 1396, 1151, 2613, 1111, 170, 20164, 10932, 2271, 7954, 1736, 1139, 2006, 1297, 119, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [9]:
tokens2 = tokenizer.tokenize(sentence)
ids2 = tokenizer.convert_tokens_to_ids(tokens2)
tokens2, ids2

(['I',
  '’',
  've',
  'been',
  'waiting',
  'for',
  'a',
  'Hu',
  '##gging',
  '##F',
  '##ace',
  'course',
  'my',
  'whole',
  'life',
  '.'],
 [146,
  787,
  1396,
  1151,
  2613,
  1111,
  170,
  20164,
  10932,
  2271,
  7954,
  1736,
  1139,
  2006,
  1297,
  119])

In [10]:
decoded_string = tokenizer.decode([146,
  787,
  1396,
  1151,
  2613,
  1111,
  170,
  20164,
  10932,
  2271,
  7954,
  1736,
  1139,
  2006,
  1297,
  119])

decoded_string

'I ’ ve been waiting for a HuggingFace course my whole life.'

In [12]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer3 = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer3.tokenize(sequence)
ids = tokenizer3.convert_tokens_to_ids(tokens)
inputs_ids = torch.tensor(ids)

model(inputs_ids)

C:\Users\user\Desktop\MlLibraries\.venv\Lib\site-packages\huggingface_hub\file_download.py:150: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in D:\huggingface_cache\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
C:\Users\user\Desktop\MlLibraries\.venv\Lib\site-packages\huggingface_hub\file_download.py:150: UserWarning: `huggingface_hub` cache-system uses symlin

RuntimeError: The size of tensor a (14) must match the size of tensor b (512) at non-singleton dimension 1

In [14]:
input_ids = torch.tensor([ids])
output = model(input_ids)
inputs_ids, output.logits

(tensor([ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]),
 tensor([[-2.7276,  2.8789]], grad_fn=<AddmmBackward0>))

In [18]:
sequence1_ids = [200, 200, 200]
sequence2_ids = [200, 200]

sequence2_ids.append(tokenizer3.pad_token_id)

batched_ids = [
    sequence1_ids,
    sequence2_ids
]

attention_mask = [
    [1, 1, 1],
    [1, 1, 0]
]

input_ids = torch.tensor(batched_ids)
mask = torch.tensor(attention_mask)

print(input_ids.shape)
print(mask.shape)

outputs = model(input_ids, attention_mask=mask)

outputs.logits

torch.Size([2, 3])
torch.Size([2, 3])


tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)

In [19]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

tokenizer("I've been waiting for a HuggingFace course my whole life.")

{'input_ids': [101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [20]:
sequences = ["I've been waiting for a HuggingFace course my whole life.", "So have I!"]
tokenizer(sequences)

{'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102], [101, 2061, 2031, 1045, 999, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}

In [ ]:
model_inputs = tokenizer(sequences, padding='longest') # Will pad the sequences up to the maximum sequence length

model_inputs = tokenizer(sequences, padding='max_length')# Will pad the sequences up to the model max length
# (512 for BERT or DistilBERT)
model_inputs = tokenizer(sequences, padding="max_length", max_length=8)# Will pad the sequences up to the specified max length


In [ ]:
model_inputs = tokenizer(sequences, truncation=True)# Will truncate the sequences that are longer than the model max length
# (512 for BERT or DistilBERT)

model_inputs = tokenizer(sequences, max_length=8, truncation=True)# Will truncate the sequences that are longer than the specified max length


In [ ]:
model_inputs = tokenizer(sequences, return_tensors='pt')# Returns PyTorch tensors

model_inputs = tokenizer(sequences, return_tensors='np')# Returns NumPy arrays


In [21]:
sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)

In [22]:
tokenizer.decode(ids)

"i ' ve been waiting for a huggingface course my whole life."

In [23]:
tokens = tokenizer(sequence)
tokenizer.decode(tokens)

"[CLS] i ' ve been waiting for a huggingface course my whole life. [SEP]"